### ISSUE TITLE
Add support for RedisJSON 2.0 full JSONPath syntax

### ISSUE THREAD

**Issue by gkorland** [mkorkmaz/redislabs-rejson#10]
Please notice all the commands can now get full jsonpath, i.e. dynamic paths that start with a $ sign.
As a result all the commands can now return multi parts of the JSON.
see: https://oss.redis.com/redisjson/commands/

**Comment by mkorkmaz** [comment]
Hi @gkorland 

Thanks for the notice. This gave me the chance to make some refactoring in the code I planned for a while. After adding some tests and updating the documentation, i will tag the new version asap.
