### ISSUE TITLE
Not support OPT_PREFIX ?

### ISSUE THREAD

**Issue by juvenrui** [mkorkmaz/redislabs-rejson#12]
Hi:

    redis set OPT_PREFIX，but rejson not support. code:

> $redis  = new \Redis();
> $redis->connect('localhost', 6379);
> _$redis->setOption(\Redis::OPT_PREFIX, 'love');_
> $redis->select(1);
> $reJSON = \Redislabs\Module\ReJSON\ReJSON::createWithPhpRedis($redis);
> $reJSON->set('doc1', '$', ['foo'=>'bar']);
> var_dump($reJSON->get('doc'));
> 
> $redis->set('doc2', 'blablabla...');
> var_dump($redis->get('doc2'));
> var_dump($reJSON->exists('doc'), $redis->exists('doc2'));

**Comment by mkorkmaz** [comment]
Hi @juvenrui 

OPT_PREFIX option issue is out of this library's scope. Probably it is not supported by RedisJson Module or PhpRedis handles it poorly.

**Comment by juvenrui** [comment]
> Hi @juvenrui
> 
> OPT_PREFIX option issue is out of this library's scope. Probably it is not supported by RedisJson Module or PhpRedis handles it poorly.

OK，thank you for your reply.
