### ISSUE TITLE
How to use this with Laravel

### ISSUE THREAD

**Issue by vishytk** [mkorkmaz/redislabs-rejson#13]
I am using Laravel v10 and want to use this library. It would be of great help if some example is shown.

**Comment by mkorkmaz** [comment]
Hi @vishytk 

You can add service providers for RedisJson. See the example for phpredis: [https://gist.github.com/mkorkmaz/d1a6c5f9fdf021c609acd6486c7deef9](https://gist.github.com/mkorkmaz/d1a6c5f9fdf021c609acd6486c7deef9). May be i should add this providers to the library, but you can use them directly.

Then you can use RedisJson in your contollers using RedisJsonInterface type hint.



```php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Redislabs\Module\RedisJson\RedisJsonInterface;

use function response;

class MyController extends Controller
{
    public function __invoke(Request $request, RedisJsonInterface $redisJson): JsonResponse
    {
        $redisJson->set('my-data', '.', ['name'=>'my name', 'age' => 33, 'items' =>['item-1', 'item-2']]);
        $data = $redisJson->get('my-data', '$.items');

        return response()->json($data);
    }
}

```

**Comment by vishytk** [comment]
> Hi @vishytk 
> 
> You can add service providers for RedisJson. See the example for phpredis: [https://gist.github.com/mkorkmaz/d1a6c5f9fdf021c609acd6486c7deef9](https://gist.github.com/mkorkmaz/d1a6c5f9fdf021c609acd6486c7deef9). May be i should add this providers to the library, but you can use them directly.
> 
> Then you can use RedisJson in your contollers using RedisJsonInterface type hint.
> 
> 
> 
> ```php
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\Http\Controllers;
> use App\Http\Controllers\Controller;
> use Illuminate\Http\JsonResponse;
> use Illuminate\Http\Request;
> use Redislabs\Module\RedisJson\RedisJsonInterface;
> 
> use function response;
> 
> class MyController extends Controller
> {
>     public function __invoke(Request $request, RedisJsonInterface $redisJson): JsonResponse
>     {
>         $redisJson->set('my-data', '.', ['name'=>'my name', 'age' => 33, 'items' =>['item-1', 'item-2']]);
>         $data = $redisJson->get('my-data', '$.items');
> 
>         return response()->json($data);
>     }
> }
> 
> ```
> 

I will try this and update.

**Comment by vishytk** [comment]
Not working for me. Here's what I have done.

added the two services providers to my code (laravel package) and registered them

In the routes file

```php
Route::get('/slots', function (RedisJsonInterface $redisJson) {
    dump($redisJson->get('timeslots'));
});
```

Test file, RedisTest
```php
<?php

it('tests redis', function () {
    $response = $this->actingAs($this->user)
        ->get("/slots", $this->headers);
    dump($response);
});
```

I am getting exception error:

"Target [Redislabs\Module\RedisJson\RedisJsonInterface] is not instantiable."

**Comment by vishytk** [comment]
got it, I had made mistake in registering the service providers properly.

Thanks for the help.

**Comment by mkorkmaz** [comment]
@vishytk I am glad you resolved your issue. Have fun.
