### ISSUE TITLE
PHP version support

### ISSUE THREAD

**Issue by indreek** [mkorkmaz/redislabs-rejson#15]
Hello

Your composer says that PHP 8.1 is required https://github.com/mkorkmaz/redislabs-rejson/blob/75a18d8bd06ab07e454e46112c413ce54249d85b/composer.json#L14.
Last git commit says that PHP 8.0 support is dropped
And about says: "Redislabs RedisJson aka ReJson Client for PHP (PHP 7.3+)".

It is bit misleading that PHP 8+ seems not to be supported.

**Comment by mkorkmaz** [comment]
Thanks for noticing, changed the old description. Could you please share any specific and reproducible issue about the mention "PHP 8+ seems not to be supported."

**Comment by indreek** [comment]
It's working fine with PHP 8.1, we just had discussion in team that according to docs PHP 8 is not supported. No issues other than misleading description.

**Comment by mkorkmaz** [comment]
Oh it just means 8.0 is not supported but 8.1 and later supported.
