### ISSUE TITLE
Set is not working 

### ISSUE THREAD

**Issue by Peace-N** [mkorkmaz/redislabs-rejson#3]
when using ->set() its not creating the entry however get() works as expected ...

**Comment by mkorkmaz** [comment]
Hi @Peace-N ,

If get() works expected then set() should also have been worked expected. To reproduce the issue, would you share the use case example and  redis/redis-rejson version for the issue? 

Thanks,

**Comment by Peace-N** [comment]
The issue seems to be happening when you use path

**Comment by Peace-N** [comment]
Hi @mkorkmaz I have managed to get it to work using a set pattern client:games:{id} and we may close this issue. I will open another issue for a bug i found and would like to create a pull request to core ...
