### ISSUE TITLE
Calling mget only works as $reJson->mget(...$keys, ...['.']);

### ISSUE THREAD

**Issue by Mulkave** [mkorkmaz/redislabs-rejson#6]
About the signature of `ReJSON::mget` and calling it with arguments, the only way i could make it work is as follows:

```php
$keys = ['key:1', 'key:2', 'key:3'];

$reJson->mget(...$keys, ...['.']);
```

> The reason for `...['.']` is because when calling `mget(...$keys, '.')` i get the following error: `Cannot use positional argument after argument unpacking`. Running PHP 7.4

Inspecting the source of `MultipleGet::createCommandWithArguments` found that it's because of this snippet:

```php
$path = array_pop($arguments);
$keys = $arguments;
return new self(
  $keys,
  new Path($path)
);
```

When calling the code with `$reJson->mget($keys, '.')` it ends up with this:

```php
array:2 [
  "path" => "."
  "keys" => array:1 [
    0 => array:3 [
      0 => "key:1"
      1 => "key:2"
      2 => "key:3"
    ]
  ]
]
```

When instead it should have been:

```php
array:2 [
  "path" => "."
  "keys" => array:3 [
    0 => "key:1"
    1 => "key:2"
    2 => "key:3"
  ]
]
```

----

This can be easily solved by replacing `$keys = $arguments;` with `$keys = array_pop($arguments);`.

1. Is it intentional for the signature to be called as such with variables? `$reJson->mget(...$keys, ...['.']);`
2. If not, i'd be happy to open a PR with this change. How about that?

**Comment by mkorkmaz** [comment]
Hi Abed,

Sorry for the issue you came across. 

I just tried to follow RedisLab ReJSON module's convention. You can see the details about JSON.MGET [here](https://oss.redislabs.com/redisjson/commands/#jsonmget).

I would just append the `path` at the end of `$keys` array instead of `$reJson->mget(...$keys, ...['.'])` See the example below.


Would you please run this piece of code and paste the result as a comment below.


```php

    $reJson->set('key:1', '.', 'value:1');
    $reJson->set('key:2', '.', 'value:2');
    $reJson->set('key:3', '.', 'value:3');
    $keysAndPath = ['key:1', 'key:2', 'key:3', '.'];
    $mgetResult = $reJson->mget(...$keysAndPath);
    var_dump($mgetResult);
```

Expected output should be like this:

```
array(3) {
  [0]=>
  string(7) "value:1"
  [1]=>
  string(7) "value:2"
  [2]=>
  string(7) "value:3"
}
```


Last thing: do you use any wrapper around this library?

Best,

Mehmet

ping @Mulkave

**Comment by Mulkave** [comment]
@mkorkmaz thanks for the answer!

> I would just append the path at the end of $keys array instead of $reJson->mget(...$keys, ...['.']) See the example below.


Yes merging both in one does it as well but it costs another variable so i'll keep the ugly version 😅 because the keys are dynamically built so it makes it a little difficult to gather everything at the end.

> Last thing: do you use any wrapper around this library?

Not sure if I understand correctly what you mean by "wrapper", but i'm simply calling the library directly `$reJson->mget(...)`

> I just tried to follow RedisLab ReJSON module's convention. You can see the details about JSON.MGET here.

I see. I had just expected the path to be a separate parameter as a string and would use the spread operator in the first parameter on the keys. *e.g.*

```php
$keys = ['key:1', 'key:2', 'key:3']
$reJson->mget(...$keys, '.')
```

Nevertheless, it's not an issue, just wanted to clarify whether it is intended to be as such.

Thanks for the clarification and for the awesome work on this library 💪
